### PR TITLE
Fix company name (replace ShowMax with Showmax)

### PR DESCRIPTION
**Pull request by jbrunclik**

### CODE REVIEW

**Review by jtomsa — APPROVED** [review]
LGTM. However I found one more appearance of ShowMax here in the vendor folder https://github.com/Showmax/sockrus/tree/master/vendor/github.com/ShowMax/go-fqdn.
I am not sure if it is relevant, it might get updated once the referenced repo is fixed?

**Comment by jbrunclik** [comment]
I'll update the contents of the `vendor` folder once https://github.com/Showmax/go-fqdn/pull/5 is landed.

**Comment by jbrunclik** [comment]
I've updated the [go-fqdn](https://github.com/Showmax/go-fqdn) vendor folder to the latest version (with updated `README.md`). Please take another look.

**Comment by jtomsa** [comment]
thanks :)
One more thing... please change the /vendor/github.com/ShowMax folder to Showmax

**Comment by jbrunclik** [comment]
Right, thanks for catching this!

Should be fine now.

**Pull request merged**
